name: Query GitHub Releases

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 0 1 * *"  # Runs on the first day of every month

jobs:
  query-releases:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      # Step 4: Run the release query script
      - name: Query GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the provided GitHub token
        run: |
          python query_releases.py

      # Step 5: Upload the results as an artifact
      - name: Upload Releases JSON
        uses: actions/upload-artifact@v3
        with:
          name: filtered-releases
          path: filtered_releases.json
