name: Query GitHub Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: read

jobs:
  query-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Token
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          python -c "import os; print('Token:', os.getenv('GITHUB_TOKEN'))"
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Query GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python query_releases.py

      - name: Upload Releases JSON
        uses: actions/upload-artifact@v3
        with:
          name: filtered-releases
          path: filtered_releases.json
